<?php
  $lang['campo1']		= 'Cotacao / Pedido';
  $lang['campo2'] 		= 'Data de abertura';
  $lang['campo3']		= 'Data de aprovacao';
  $lang['campo4']		= 'Prazo de entrega';
  $lang['origem'] 		= 'Loja';
  $lang['destino'] 		= 'Fornecedor';
  $lang['descricao'] 	= 'Produto';
  $lang['descricao2'] 	= 'Cod. Barras';
  $lang['quant'] 		= 'Quant';
  $lang['preco'] 		= 'Valor';
  $lang['desconto'] 	= 'Desconto';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Pagina';
  $lang['page_of'] 		= 'de';
?>